---
- name: Create EC2 instances and R53 records
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0adfe78ec6189cd05
    zone_id: Z03460353RS4GS5RQB39D
    domain_name: "believeinyou.fun"
    instances:
    - mongodb

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{item}}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ami_id}}"
      tags:
        Name: "{{item}}"
      register: ec2_output  

    loop: "{{instances}}"

  - name: Print the EC2 output
    ansible.builtin.debug:
      msg: "{{ec2_output}}" 