--- 
- name: Setting up catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable current module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable required module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install NodeJS
    ansible.builtin.dnf: 
      name: nodejs 
      state: present

  - name: Add application User- System User   
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      home: /app
      # home: Optionally set the user’s home directory.     
      system: true
      # system: When creating an account state=present, setting this to true makes the user a system account.
      shell: /sbin/nologin
      # shell:Optionally set the user’s shell.


  - name: Lets setup an app directory.
    ansible.builtin.file:
      path: /app  
      state: directory  

  - name: Download the application code 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
      # dest: Absolute path of where to download the file to.     